apiVersion: v1
kind: Service
metadata:
  name: alb-nodejs
  namespace: alb-nodejs
spec:
  selector:
    app: alb-nodejs
  ports:
    - protocol: TCP
      port: 8080         # Service port
      targetPort: 8080   # Pod/container port
      nodePort: 30080    # Optional: NodePort (range 30000–32767); omit to auto-assign
  type: NodePort
