apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: alb-nodejs
  name: alb-nodejs
  annotations:
    argocd-image-updater.argoproj.io/image-list: app=263652000820.dkr.ecr.ap-south-1.amazonaws.com/akashplay
spec:
  replicas: 2
  selector:
    matchLabels:
      app: alb-nodejs
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: alb-nodejs
    spec:
      containers:
      - image: 263652000820.dkr.ecr.ap-south-1.amazonaws.com/akashplay:latest
        name: akashplay
      imagePullSecrets:
      - name: ecr-secret
