apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: alb-nodejs
  name: alb-nodejs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: alb-nodejs
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: alb-nodejs
    spec:
      containers:
      - image: nginx
        name: akashplay
        resources: {}
status: {}
