name: Auto-merge PRs

on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}

jobs:
  validate-manifests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install yamllint
        run: pip install yamllint
      
      - name: Lint YAML files
        run: yamllint .
      
      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        
      - name: Validate Kubernetes manifests
        run: |
          find . -name "*.yaml" -type f -exec kubectl apply --dry-run=client -f {} \;

  auto-merge:
    needs: validate-manifests
    runs-on: ubuntu-latest
    steps:
      - name: Auto-merge PR
        uses: pascalgn/automerge-action@v0.15.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          merge-method: squash
          label: automerge